import Link from "next/link";
import { ArrowRight, HeartHandshake, MonitorPlay, Printer, ShieldCheck, Smartphone, Sparkles } from "lucide-react";
import { SiteShell } from "./site-shell";
import {CallToAction} from "./call-to-action";
const products=[{icon:Printer,no:"01",title:"그림 중심 인쇄 안내지",text:"어르신도 한눈에 이해할 수 있는 치료별 주의사항",meta:"인쇄용 · PDF · 그림 안내"},{icon:Smartphone,no:"02",title:"휴대폰 안내 콘텐츠",text:"진료실 설명을 집에서도 다시 확인하는 모바일 자료",meta:"문자 · QR · 이미지"},{icon:MonitorPlay,no:"03",title:"대기실 교육 콘텐츠",text:"대기 중에도 핵심 안내를 쉽게 접하는 화면 자료",meta:"화면 · 슬라이드 · 영상"},{icon:Sparkles,no:"04",title:"참여형 교육 게임",text:"환자가 직접 풀며 기억하는 쉽고 재미있는 콘텐츠",meta:"퀴즈 · 터치 · 반복 학습"}];
export default function Home(){return <SiteShell>
<section className="hero wrap"><div className="hero-copy"><span className="eyebrow">환자에게는 쉬운 이해 · 치과에는 효율적인 전달</span><h1>진료실에서 들은 설명,<br/><em>집에서도 기억되게.</em></h1><p>브릿지덴탈노트는 복잡한 치과 정보를 그림과 쉬운 말로 바꾸고, 반복되는 환자 안내 업무를 더 빠르고 편하게 만듭니다.</p><div className="hero-actions"><Link className="btn primary" href="/sample">무료 샘플 받아보기 <ArrowRight size={18}/></Link><Link className="text-link" href="/products">제품 살펴보기</Link></div><div className="trust-line"><ShieldCheck size={18}/><span>경력 치과위생사의 현장 경험을 바탕으로 제작합니다</span></div></div>
<div className="hero-visual" aria-label="치과 안내 콘텐츠 예시"><div className="sheet sheet-main"><div className="sheet-tag">안내자료 구성 예시</div><div className="tooth-icon">🦷</div><h3>치료 후 안내<br/>꼭 기억해 주세요</h3><div className="mini-row"><span>01</span><b>꼭 기억할 내용</b></div><div className="mini-row"><span>02</span><b>집에서 확인할 내용</b></div><div className="mini-row"><span>03</span><b>치과에 물어볼 내용</b></div></div><div className="phone-card"><div className="phone-notch"/><span>BRIDGE DENTAL NOTE</span><div className="phone-art">✓</div><b>집에서도<br/>한 번 더 확인하세요</b></div><div className="note-pill"><HeartHandshake size={22}/><span>쉬운 설명이<br/><b>좋은 진료 경험</b>으로</span></div></div></section>
<section className="problem-band"><div className="wrap problem-grid"><div><span className="section-kicker">THE PROBLEM</span><h2>설명은 반복되는데,<br/>환자에게는 잘 남지 않습니다.</h2></div><div className="problem-list"><p>“집에 오니 주의사항이 기억나지 않아요.”</p><p>“같은 설명을 하루에도 몇 번씩 반복해요.”</p><p>“글이 많으면 어르신들이 읽기 어려워하세요.”</p></div></div></section>
<section className="section wrap"><div className="section-head"><div><span className="section-kicker">WHAT WE MAKE</span><h2>한 번 만들고, 여러 번 쓰는<br/>환자 안내 도구</h2></div><p>인쇄물부터 휴대폰, 대기실 화면까지<br/>치과 상황에 맞게 연결합니다.</p></div><div className="product-grid">{products.map(({icon:Icon,...p})=><article className="product-card" key={p.no}><div className="product-top"><span>{p.no}</span><Icon size={25}/></div><h3>{p.title}</h3><p>{p.text}</p><small>{p.meta}</small></article>)}</div><div className="center"><Link className="text-link arrow" href="/products">전체 제품 자세히 보기 <ArrowRight size={17}/></Link></div></section>
<section className="section navy"><div className="wrap why-grid"><div><span className="section-kicker light">WHY BRIDGE</span><h2>예쁘기만 한 자료가 아니라,<br/><em>현장에서 실제로 쓰이는 자료.</em></h2></div><div className="why-items"><div><span>01</span><h3>현장 언어</h3><p>치과 진료 흐름과 환자의 실제 질문을 반영합니다.</p></div><div><span>02</span><h3>어르신 우선</h3><p>큰 글씨, 짧은 문장, 직관적인 그림으로 만듭니다.</p></div><div><span>03</span><h3>반복 사용</h3><p>인쇄·문자·QR·대기실 화면에서 계속 활용할 수 있습니다.</p></div></div></div></section>
<section className="section wrap process"><div className="section-head"><div><span className="section-kicker">HOW IT WORKS</span><h2>도입은 가볍게,<br/>안내는 꾸준하게</h2></div></div><div className="steps"><div><b>01</b><h3>필요한 자료 선택</h3><p>우리 치과에서 반복되는 설명을 고릅니다.</p></div><ArrowRight/><div><b>02</b><h3>치과에 맞게 적용</h3><p>로고와 안내 방식을 진료 흐름에 맞춥니다.</p></div><ArrowRight/><div><b>03</b><h3>여러 채널에서 반복 사용</h3><p>출력하고, 전송하고, 대기실에서 보여줍니다.</p></div></div></section>
<CallToAction/>
</SiteShell>}
